// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CTRL_CAMNET_V1_H_
#define FLATBUFFERS_GENERATED_CTRL_CAMNET_V1_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace camnet {
namespace v1 {

struct BringupMessage;
struct BringupMessageBuilder;

struct OpenArgs;
struct OpenArgsBuilder;

struct StartThreadsArgs;
struct StartThreadsArgsBuilder;

struct StartArgs;
struct StartArgsBuilder;

struct StopArgs;
struct StopArgsBuilder;

struct ReplyInfo;
struct ReplyInfoBuilder;

struct Server;
struct ServerBuilder;

enum Kind : uint8_t {
  Kind_KindCommand = 0,
  Kind_KindReply = 1,
  Kind_MIN = Kind_KindCommand,
  Kind_MAX = Kind_KindReply
};

inline const Kind (&EnumValuesKind())[2] {
  static const Kind values[] = {
    Kind_KindCommand,
    Kind_KindReply
  };
  return values;
}

inline const char * const *EnumNamesKind() {
  static const char * const names[3] = {
    "KindCommand",
    "KindReply",
    nullptr
  };
  return names;
}

inline const char *EnumNameKind(Kind e) {
  if (::flatbuffers::IsOutRange(e, Kind_KindCommand, Kind_KindReply)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesKind()[index];
}

enum ServerControl : uint8_t {
  ServerControl_NONE = 0,
  ServerControl_OPENCAMERA = 1,
  ServerControl_STARTTHREAD = 2,
  ServerControl_STARTRECORDING = 3,
  ServerControl_STOPRECORDING = 4,
  ServerControl_TEARDOWN = 5,
  ServerControl_MIN = ServerControl_NONE,
  ServerControl_MAX = ServerControl_TEARDOWN
};

inline const ServerControl (&EnumValuesServerControl())[6] {
  static const ServerControl values[] = {
    ServerControl_NONE,
    ServerControl_OPENCAMERA,
    ServerControl_STARTTHREAD,
    ServerControl_STARTRECORDING,
    ServerControl_STOPRECORDING,
    ServerControl_TEARDOWN
  };
  return values;
}

inline const char * const *EnumNamesServerControl() {
  static const char * const names[7] = {
    "NONE",
    "OPENCAMERA",
    "STARTTHREAD",
    "STARTRECORDING",
    "STOPRECORDING",
    "TEARDOWN",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerControl(ServerControl e) {
  if (::flatbuffers::IsOutRange(e, ServerControl_NONE, ServerControl_TEARDOWN)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerControl()[index];
}

enum CommandBody : uint8_t {
  CommandBody_NONE = 0,
  CommandBody_OpenArgs = 1,
  CommandBody_StartThreadsArgs = 2,
  CommandBody_StartArgs = 3,
  CommandBody_StopArgs = 4,
  CommandBody_MIN = CommandBody_NONE,
  CommandBody_MAX = CommandBody_StopArgs
};

inline const CommandBody (&EnumValuesCommandBody())[5] {
  static const CommandBody values[] = {
    CommandBody_NONE,
    CommandBody_OpenArgs,
    CommandBody_StartThreadsArgs,
    CommandBody_StartArgs,
    CommandBody_StopArgs
  };
  return values;
}

inline const char * const *EnumNamesCommandBody() {
  static const char * const names[6] = {
    "NONE",
    "OpenArgs",
    "StartThreadsArgs",
    "StartArgs",
    "StopArgs",
    nullptr
  };
  return names;
}

inline const char *EnumNameCommandBody(CommandBody e) {
  if (::flatbuffers::IsOutRange(e, CommandBody_NONE, CommandBody_StopArgs)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCommandBody()[index];
}

template<typename T> struct CommandBodyTraits {
  static const CommandBody enum_value = CommandBody_NONE;
};

template<> struct CommandBodyTraits<camnet::v1::OpenArgs> {
  static const CommandBody enum_value = CommandBody_OpenArgs;
};

template<> struct CommandBodyTraits<camnet::v1::StartThreadsArgs> {
  static const CommandBody enum_value = CommandBody_StartThreadsArgs;
};

template<> struct CommandBodyTraits<camnet::v1::StartArgs> {
  static const CommandBody enum_value = CommandBody_StartArgs;
};

template<> struct CommandBodyTraits<camnet::v1::StopArgs> {
  static const CommandBody enum_value = CommandBody_StopArgs;
};

bool VerifyCommandBody(::flatbuffers::Verifier &verifier, const void *obj, CommandBody type);
bool VerifyCommandBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct BringupMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BringupMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_NAME = 4,
    VT_NUM_CAMERAS = 6
  };
  const ::flatbuffers::String *server_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SERVER_NAME);
  }
  uint16_t num_cameras() const {
    return GetField<uint16_t>(VT_NUM_CAMERAS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SERVER_NAME) &&
           verifier.VerifyString(server_name()) &&
           VerifyField<uint16_t>(verifier, VT_NUM_CAMERAS, 2) &&
           verifier.EndTable();
  }
};

struct BringupMessageBuilder {
  typedef BringupMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_name(::flatbuffers::Offset<::flatbuffers::String> server_name) {
    fbb_.AddOffset(BringupMessage::VT_SERVER_NAME, server_name);
  }
  void add_num_cameras(uint16_t num_cameras) {
    fbb_.AddElement<uint16_t>(BringupMessage::VT_NUM_CAMERAS, num_cameras, 0);
  }
  explicit BringupMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BringupMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BringupMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BringupMessage> CreateBringupMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> server_name = 0,
    uint16_t num_cameras = 0) {
  BringupMessageBuilder builder_(_fbb);
  builder_.add_server_name(server_name);
  builder_.add_num_cameras(num_cameras);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BringupMessage> CreateBringupMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *server_name = nullptr,
    uint16_t num_cameras = 0) {
  auto server_name__ = server_name ? _fbb.CreateString(server_name) : 0;
  return camnet::v1::CreateBringupMessage(
      _fbb,
      server_name__,
      num_cameras);
}

struct OpenArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OpenArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONFIG_FOLDER = 4
  };
  const ::flatbuffers::String *config_folder() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONFIG_FOLDER);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CONFIG_FOLDER) &&
           verifier.VerifyString(config_folder()) &&
           verifier.EndTable();
  }
};

struct OpenArgsBuilder {
  typedef OpenArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_config_folder(::flatbuffers::Offset<::flatbuffers::String> config_folder) {
    fbb_.AddOffset(OpenArgs::VT_CONFIG_FOLDER, config_folder);
  }
  explicit OpenArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OpenArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OpenArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OpenArgs> CreateOpenArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> config_folder = 0) {
  OpenArgsBuilder builder_(_fbb);
  builder_.add_config_folder(config_folder);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OpenArgs> CreateOpenArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *config_folder = nullptr) {
  auto config_folder__ = config_folder ? _fbb.CreateString(config_folder) : 0;
  return camnet::v1::CreateOpenArgs(
      _fbb,
      config_folder__);
}

struct StartThreadsArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartThreadsArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RECORD_FOLDER = 4,
    VT_ENCODER_SETUP = 6
  };
  const ::flatbuffers::String *record_folder() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RECORD_FOLDER);
  }
  const ::flatbuffers::String *encoder_setup() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENCODER_SETUP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_RECORD_FOLDER) &&
           verifier.VerifyString(record_folder()) &&
           VerifyOffset(verifier, VT_ENCODER_SETUP) &&
           verifier.VerifyString(encoder_setup()) &&
           verifier.EndTable();
  }
};

struct StartThreadsArgsBuilder {
  typedef StartThreadsArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_record_folder(::flatbuffers::Offset<::flatbuffers::String> record_folder) {
    fbb_.AddOffset(StartThreadsArgs::VT_RECORD_FOLDER, record_folder);
  }
  void add_encoder_setup(::flatbuffers::Offset<::flatbuffers::String> encoder_setup) {
    fbb_.AddOffset(StartThreadsArgs::VT_ENCODER_SETUP, encoder_setup);
  }
  explicit StartThreadsArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartThreadsArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartThreadsArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartThreadsArgs> CreateStartThreadsArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> record_folder = 0,
    ::flatbuffers::Offset<::flatbuffers::String> encoder_setup = 0) {
  StartThreadsArgsBuilder builder_(_fbb);
  builder_.add_encoder_setup(encoder_setup);
  builder_.add_record_folder(record_folder);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StartThreadsArgs> CreateStartThreadsArgsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *record_folder = nullptr,
    const char *encoder_setup = nullptr) {
  auto record_folder__ = record_folder ? _fbb.CreateString(record_folder) : 0;
  auto encoder_setup__ = encoder_setup ? _fbb.CreateString(encoder_setup) : 0;
  return camnet::v1::CreateStartThreadsArgs(
      _fbb,
      record_folder__,
      encoder_setup__);
}

struct StartArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PTP_TIME = 4
  };
  uint64_t ptp_time() const {
    return GetField<uint64_t>(VT_PTP_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_PTP_TIME, 8) &&
           verifier.EndTable();
  }
};

struct StartArgsBuilder {
  typedef StartArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ptp_time(uint64_t ptp_time) {
    fbb_.AddElement<uint64_t>(StartArgs::VT_PTP_TIME, ptp_time, 0);
  }
  explicit StartArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartArgs> CreateStartArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t ptp_time = 0) {
  StartArgsBuilder builder_(_fbb);
  builder_.add_ptp_time(ptp_time);
  return builder_.Finish();
}

struct StopArgs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StopArgsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PTP_TIME = 4
  };
  uint64_t ptp_time() const {
    return GetField<uint64_t>(VT_PTP_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_PTP_TIME, 8) &&
           verifier.EndTable();
  }
};

struct StopArgsBuilder {
  typedef StopArgs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ptp_time(uint64_t ptp_time) {
    fbb_.AddElement<uint64_t>(StopArgs::VT_PTP_TIME, ptp_time, 0);
  }
  explicit StopArgsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StopArgs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StopArgs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StopArgs> CreateStopArgs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t ptp_time = 0) {
  StopArgsBuilder builder_(_fbb);
  builder_.add_ptp_time(ptp_time);
  return builder_.Finish();
}

struct ReplyInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReplyInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OK = 4,
    VT_CODE = 6,
    VT_DETAIL = 8,
    VT_BRINGUP = 10,
    VT_SERVER_ID = 12
  };
  bool ok() const {
    return GetField<uint8_t>(VT_OK, 1) != 0;
  }
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  const ::flatbuffers::String *detail() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DETAIL);
  }
  const camnet::v1::BringupMessage *bringup() const {
    return GetPointer<const camnet::v1::BringupMessage *>(VT_BRINGUP);
  }
  const ::flatbuffers::String *server_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SERVER_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_OK, 1) &&
           VerifyField<int32_t>(verifier, VT_CODE, 4) &&
           VerifyOffset(verifier, VT_DETAIL) &&
           verifier.VerifyString(detail()) &&
           VerifyOffset(verifier, VT_BRINGUP) &&
           verifier.VerifyTable(bringup()) &&
           VerifyOffset(verifier, VT_SERVER_ID) &&
           verifier.VerifyString(server_id()) &&
           verifier.EndTable();
  }
};

struct ReplyInfoBuilder {
  typedef ReplyInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ok(bool ok) {
    fbb_.AddElement<uint8_t>(ReplyInfo::VT_OK, static_cast<uint8_t>(ok), 1);
  }
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(ReplyInfo::VT_CODE, code, 0);
  }
  void add_detail(::flatbuffers::Offset<::flatbuffers::String> detail) {
    fbb_.AddOffset(ReplyInfo::VT_DETAIL, detail);
  }
  void add_bringup(::flatbuffers::Offset<camnet::v1::BringupMessage> bringup) {
    fbb_.AddOffset(ReplyInfo::VT_BRINGUP, bringup);
  }
  void add_server_id(::flatbuffers::Offset<::flatbuffers::String> server_id) {
    fbb_.AddOffset(ReplyInfo::VT_SERVER_ID, server_id);
  }
  explicit ReplyInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReplyInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReplyInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReplyInfo> CreateReplyInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool ok = true,
    int32_t code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> detail = 0,
    ::flatbuffers::Offset<camnet::v1::BringupMessage> bringup = 0,
    ::flatbuffers::Offset<::flatbuffers::String> server_id = 0) {
  ReplyInfoBuilder builder_(_fbb);
  builder_.add_server_id(server_id);
  builder_.add_bringup(bringup);
  builder_.add_detail(detail);
  builder_.add_code(code);
  builder_.add_ok(ok);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReplyInfo> CreateReplyInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool ok = true,
    int32_t code = 0,
    const char *detail = nullptr,
    ::flatbuffers::Offset<camnet::v1::BringupMessage> bringup = 0,
    const char *server_id = nullptr) {
  auto detail__ = detail ? _fbb.CreateString(detail) : 0;
  auto server_id__ = server_id ? _fbb.CreateString(server_id) : 0;
  return camnet::v1::CreateReplyInfo(
      _fbb,
      ok,
      code,
      detail__,
      bringup,
      server_id__);
}

struct Server FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_CONTROL = 6,
    VT_JOB_ID = 8,
    VT_EPOCH = 10,
    VT_SEQ = 12,
    VT_COMMAND_BODY_TYPE = 14,
    VT_COMMAND_BODY = 16,
    VT_REPLY = 18
  };
  camnet::v1::Kind kind() const {
    return static_cast<camnet::v1::Kind>(GetField<uint8_t>(VT_KIND, 0));
  }
  camnet::v1::ServerControl control() const {
    return static_cast<camnet::v1::ServerControl>(GetField<uint8_t>(VT_CONTROL, 0));
  }
  const ::flatbuffers::String *job_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_JOB_ID);
  }
  uint32_t epoch() const {
    return GetField<uint32_t>(VT_EPOCH, 0);
  }
  uint32_t seq() const {
    return GetField<uint32_t>(VT_SEQ, 0);
  }
  camnet::v1::CommandBody command_body_type() const {
    return static_cast<camnet::v1::CommandBody>(GetField<uint8_t>(VT_COMMAND_BODY_TYPE, 0));
  }
  const void *command_body() const {
    return GetPointer<const void *>(VT_COMMAND_BODY);
  }
  template<typename T> const T *command_body_as() const;
  const camnet::v1::OpenArgs *command_body_as_OpenArgs() const {
    return command_body_type() == camnet::v1::CommandBody_OpenArgs ? static_cast<const camnet::v1::OpenArgs *>(command_body()) : nullptr;
  }
  const camnet::v1::StartThreadsArgs *command_body_as_StartThreadsArgs() const {
    return command_body_type() == camnet::v1::CommandBody_StartThreadsArgs ? static_cast<const camnet::v1::StartThreadsArgs *>(command_body()) : nullptr;
  }
  const camnet::v1::StartArgs *command_body_as_StartArgs() const {
    return command_body_type() == camnet::v1::CommandBody_StartArgs ? static_cast<const camnet::v1::StartArgs *>(command_body()) : nullptr;
  }
  const camnet::v1::StopArgs *command_body_as_StopArgs() const {
    return command_body_type() == camnet::v1::CommandBody_StopArgs ? static_cast<const camnet::v1::StopArgs *>(command_body()) : nullptr;
  }
  const camnet::v1::ReplyInfo *reply() const {
    return GetPointer<const camnet::v1::ReplyInfo *>(VT_REPLY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_KIND, 1) &&
           VerifyField<uint8_t>(verifier, VT_CONTROL, 1) &&
           VerifyOffset(verifier, VT_JOB_ID) &&
           verifier.VerifyString(job_id()) &&
           VerifyField<uint32_t>(verifier, VT_EPOCH, 4) &&
           VerifyField<uint32_t>(verifier, VT_SEQ, 4) &&
           VerifyField<uint8_t>(verifier, VT_COMMAND_BODY_TYPE, 1) &&
           VerifyOffset(verifier, VT_COMMAND_BODY) &&
           VerifyCommandBody(verifier, command_body(), command_body_type()) &&
           VerifyOffset(verifier, VT_REPLY) &&
           verifier.VerifyTable(reply()) &&
           verifier.EndTable();
  }
};

template<> inline const camnet::v1::OpenArgs *Server::command_body_as<camnet::v1::OpenArgs>() const {
  return command_body_as_OpenArgs();
}

template<> inline const camnet::v1::StartThreadsArgs *Server::command_body_as<camnet::v1::StartThreadsArgs>() const {
  return command_body_as_StartThreadsArgs();
}

template<> inline const camnet::v1::StartArgs *Server::command_body_as<camnet::v1::StartArgs>() const {
  return command_body_as_StartArgs();
}

template<> inline const camnet::v1::StopArgs *Server::command_body_as<camnet::v1::StopArgs>() const {
  return command_body_as_StopArgs();
}

struct ServerBuilder {
  typedef Server Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(camnet::v1::Kind kind) {
    fbb_.AddElement<uint8_t>(Server::VT_KIND, static_cast<uint8_t>(kind), 0);
  }
  void add_control(camnet::v1::ServerControl control) {
    fbb_.AddElement<uint8_t>(Server::VT_CONTROL, static_cast<uint8_t>(control), 0);
  }
  void add_job_id(::flatbuffers::Offset<::flatbuffers::String> job_id) {
    fbb_.AddOffset(Server::VT_JOB_ID, job_id);
  }
  void add_epoch(uint32_t epoch) {
    fbb_.AddElement<uint32_t>(Server::VT_EPOCH, epoch, 0);
  }
  void add_seq(uint32_t seq) {
    fbb_.AddElement<uint32_t>(Server::VT_SEQ, seq, 0);
  }
  void add_command_body_type(camnet::v1::CommandBody command_body_type) {
    fbb_.AddElement<uint8_t>(Server::VT_COMMAND_BODY_TYPE, static_cast<uint8_t>(command_body_type), 0);
  }
  void add_command_body(::flatbuffers::Offset<void> command_body) {
    fbb_.AddOffset(Server::VT_COMMAND_BODY, command_body);
  }
  void add_reply(::flatbuffers::Offset<camnet::v1::ReplyInfo> reply) {
    fbb_.AddOffset(Server::VT_REPLY, reply);
  }
  explicit ServerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Server> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Server>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Server> CreateServer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    camnet::v1::Kind kind = camnet::v1::Kind_KindCommand,
    camnet::v1::ServerControl control = camnet::v1::ServerControl_NONE,
    ::flatbuffers::Offset<::flatbuffers::String> job_id = 0,
    uint32_t epoch = 0,
    uint32_t seq = 0,
    camnet::v1::CommandBody command_body_type = camnet::v1::CommandBody_NONE,
    ::flatbuffers::Offset<void> command_body = 0,
    ::flatbuffers::Offset<camnet::v1::ReplyInfo> reply = 0) {
  ServerBuilder builder_(_fbb);
  builder_.add_reply(reply);
  builder_.add_command_body(command_body);
  builder_.add_seq(seq);
  builder_.add_epoch(epoch);
  builder_.add_job_id(job_id);
  builder_.add_command_body_type(command_body_type);
  builder_.add_control(control);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Server> CreateServerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    camnet::v1::Kind kind = camnet::v1::Kind_KindCommand,
    camnet::v1::ServerControl control = camnet::v1::ServerControl_NONE,
    const char *job_id = nullptr,
    uint32_t epoch = 0,
    uint32_t seq = 0,
    camnet::v1::CommandBody command_body_type = camnet::v1::CommandBody_NONE,
    ::flatbuffers::Offset<void> command_body = 0,
    ::flatbuffers::Offset<camnet::v1::ReplyInfo> reply = 0) {
  auto job_id__ = job_id ? _fbb.CreateString(job_id) : 0;
  return camnet::v1::CreateServer(
      _fbb,
      kind,
      control,
      job_id__,
      epoch,
      seq,
      command_body_type,
      command_body,
      reply);
}

inline bool VerifyCommandBody(::flatbuffers::Verifier &verifier, const void *obj, CommandBody type) {
  switch (type) {
    case CommandBody_NONE: {
      return true;
    }
    case CommandBody_OpenArgs: {
      auto ptr = reinterpret_cast<const camnet::v1::OpenArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CommandBody_StartThreadsArgs: {
      auto ptr = reinterpret_cast<const camnet::v1::StartThreadsArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CommandBody_StartArgs: {
      auto ptr = reinterpret_cast<const camnet::v1::StartArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case CommandBody_StopArgs: {
      auto ptr = reinterpret_cast<const camnet::v1::StopArgs *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyCommandBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCommandBody(
        verifier,  values->Get(i), types->GetEnum<CommandBody>(i))) {
      return false;
    }
  }
  return true;
}

inline const camnet::v1::Server *GetServer(const void *buf) {
  return ::flatbuffers::GetRoot<camnet::v1::Server>(buf);
}

inline const camnet::v1::Server *GetSizePrefixedServer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<camnet::v1::Server>(buf);
}

inline bool VerifyServerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<camnet::v1::Server>(nullptr);
}

inline bool VerifySizePrefixedServerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<camnet::v1::Server>(nullptr);
}

inline void FinishServerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<camnet::v1::Server> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedServerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<camnet::v1::Server> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace v1
}  // namespace camnet

#endif  // FLATBUFFERS_GENERATED_CTRL_CAMNET_V1_H_
