// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FETCH_FETCHGAME_H_
#define FLATBUFFERS_GENERATED_FETCH_FETCHGAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace FetchGame {

struct Server;
struct ServerBuilder;

enum ServerControl : int8_t {
  ServerControl_IDEL = 0,
  ServerControl_START = 1,
  ServerControl_SETPTP = 2,
  ServerControl_QUIT = 3,
  ServerControl_MIN = ServerControl_IDEL,
  ServerControl_MAX = ServerControl_QUIT
};

inline const ServerControl (&EnumValuesServerControl())[4] {
  static const ServerControl values[] = {
    ServerControl_IDEL,
    ServerControl_START,
    ServerControl_SETPTP,
    ServerControl_QUIT
  };
  return values;
}

inline const char * const *EnumNamesServerControl() {
  static const char * const names[5] = {
    "IDEL",
    "START",
    "SETPTP",
    "QUIT",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerControl(ServerControl e) {
  if (::flatbuffers::IsOutRange(e, ServerControl_IDEL, ServerControl_QUIT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerControl()[index];
}

struct Server FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTROL = 4,
    VT_PTP_GLOBAL_TIME = 6
  };
  FetchGame::ServerControl control() const {
    return static_cast<FetchGame::ServerControl>(GetField<int8_t>(VT_CONTROL, 0));
  }
  uint64_t ptp_global_time() const {
    return GetField<uint64_t>(VT_PTP_GLOBAL_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_CONTROL, 1) &&
           VerifyField<uint64_t>(verifier, VT_PTP_GLOBAL_TIME, 8) &&
           verifier.EndTable();
  }
};

struct ServerBuilder {
  typedef Server Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_control(FetchGame::ServerControl control) {
    fbb_.AddElement<int8_t>(Server::VT_CONTROL, static_cast<int8_t>(control), 0);
  }
  void add_ptp_global_time(uint64_t ptp_global_time) {
    fbb_.AddElement<uint64_t>(Server::VT_PTP_GLOBAL_TIME, ptp_global_time, 0);
  }
  explicit ServerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Server> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Server>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Server> CreateServer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FetchGame::ServerControl control = FetchGame::ServerControl_IDEL,
    uint64_t ptp_global_time = 0) {
  ServerBuilder builder_(_fbb);
  builder_.add_ptp_global_time(ptp_global_time);
  builder_.add_control(control);
  return builder_.Finish();
}

inline const FetchGame::Server *GetServer(const void *buf) {
  return ::flatbuffers::GetRoot<FetchGame::Server>(buf);
}

inline const FetchGame::Server *GetSizePrefixedServer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FetchGame::Server>(buf);
}

inline bool VerifyServerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<FetchGame::Server>(nullptr);
}

inline bool VerifySizePrefixedServerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<FetchGame::Server>(nullptr);
}

inline void FinishServerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FetchGame::Server> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedServerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FetchGame::Server> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FetchGame

#endif  // FLATBUFFERS_GENERATED_FETCH_FETCHGAME_H_
