// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGEWRAPPER_ORANGE_NETWORK_H_
#define FLATBUFFERS_GENERATED_MESSAGEWRAPPER_ORANGE_NETWORK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "fetch_generated.h"
#include "yolo_payload_generated.h"

namespace Orange {
namespace Network {

struct RootMessage;
struct RootMessageBuilder;
struct RootMessageT;

enum MessagePayload : int8_t {
  MessagePayload_NONE = 0,
  MessagePayload_FetchGame_Server = 1,
  MessagePayload_Orange_VisionData_YoloFrameDetections = 2,
  MessagePayload_MIN = MessagePayload_NONE,
  MessagePayload_MAX = MessagePayload_Orange_VisionData_YoloFrameDetections
};

inline const MessagePayload (&EnumValuesMessagePayload())[3] {
  static const MessagePayload values[] = {
    MessagePayload_NONE,
    MessagePayload_FetchGame_Server,
    MessagePayload_Orange_VisionData_YoloFrameDetections
  };
  return values;
}

inline const char * const *EnumNamesMessagePayload() {
  static const char * const names[4] = {
    "NONE",
    "FetchGame_Server",
    "Orange_VisionData_YoloFrameDetections",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessagePayload(MessagePayload e) {
  if (::flatbuffers::IsOutRange(e, MessagePayload_NONE, MessagePayload_Orange_VisionData_YoloFrameDetections)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessagePayload()[index];
}

enum Payload : uint8_t {
  Payload_NONE = 0,
  Payload_FetchGame_Server = 1,
  Payload_Orange_VisionData_YoloFrameDetections = 2,
  Payload_MIN = Payload_NONE,
  Payload_MAX = Payload_Orange_VisionData_YoloFrameDetections
};

inline const Payload (&EnumValuesPayload())[3] {
  static const Payload values[] = {
    Payload_NONE,
    Payload_FetchGame_Server,
    Payload_Orange_VisionData_YoloFrameDetections
  };
  return values;
}

inline const char * const *EnumNamesPayload() {
  static const char * const names[4] = {
    "NONE",
    "FetchGame_Server",
    "Orange_VisionData_YoloFrameDetections",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayload(Payload e) {
  if (::flatbuffers::IsOutRange(e, Payload_NONE, Payload_Orange_VisionData_YoloFrameDetections)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayload()[index];
}

template<typename T> struct PayloadTraits {
  static const Payload enum_value = Payload_NONE;
};

template<> struct PayloadTraits<FetchGame::Server> {
  static const Payload enum_value = Payload_FetchGame_Server;
};

template<> struct PayloadTraits<Orange::VisionData::YoloFrameDetections> {
  static const Payload enum_value = Payload_Orange_VisionData_YoloFrameDetections;
};

template<typename T> struct PayloadUnionTraits {
  static const Payload enum_value = Payload_NONE;
};

template<> struct PayloadUnionTraits<FetchGame::ServerT> {
  static const Payload enum_value = Payload_FetchGame_Server;
};

template<> struct PayloadUnionTraits<Orange::VisionData::YoloFrameDetectionsT> {
  static const Payload enum_value = Payload_Orange_VisionData_YoloFrameDetections;
};

struct PayloadUnion {
  Payload type;
  void *value;

  PayloadUnion() : type(Payload_NONE), value(nullptr) {}
  PayloadUnion(PayloadUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Payload_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  PayloadUnion(const PayloadUnion &);
  PayloadUnion &operator=(const PayloadUnion &u)
    { PayloadUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  PayloadUnion &operator=(PayloadUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~PayloadUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = PayloadUnionTraits<RT>::enum_value;
    if (type != Payload_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, Payload type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  FetchGame::ServerT *AsFetchGame_Server() {
    return type == Payload_FetchGame_Server ?
      reinterpret_cast<FetchGame::ServerT *>(value) : nullptr;
  }
  const FetchGame::ServerT *AsFetchGame_Server() const {
    return type == Payload_FetchGame_Server ?
      reinterpret_cast<const FetchGame::ServerT *>(value) : nullptr;
  }
  Orange::VisionData::YoloFrameDetectionsT *AsOrange_VisionData_YoloFrameDetections() {
    return type == Payload_Orange_VisionData_YoloFrameDetections ?
      reinterpret_cast<Orange::VisionData::YoloFrameDetectionsT *>(value) : nullptr;
  }
  const Orange::VisionData::YoloFrameDetectionsT *AsOrange_VisionData_YoloFrameDetections() const {
    return type == Payload_Orange_VisionData_YoloFrameDetections ?
      reinterpret_cast<const Orange::VisionData::YoloFrameDetectionsT *>(value) : nullptr;
  }
};

bool VerifyPayload(::flatbuffers::Verifier &verifier, const void *obj, Payload type);
bool VerifyPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct RootMessageT : public ::flatbuffers::NativeTable {
  typedef RootMessage TableType;
  Orange::Network::PayloadUnion payload{};
};

struct RootMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RootMessageT NativeTableType;
  typedef RootMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  Orange::Network::Payload payload_type() const {
    return static_cast<Orange::Network::Payload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const FetchGame::Server *payload_as_FetchGame_Server() const {
    return payload_type() == Orange::Network::Payload_FetchGame_Server ? static_cast<const FetchGame::Server *>(payload()) : nullptr;
  }
  const Orange::VisionData::YoloFrameDetections *payload_as_Orange_VisionData_YoloFrameDetections() const {
    return payload_type() == Orange::Network::Payload_Orange_VisionData_YoloFrameDetections ? static_cast<const Orange::VisionData::YoloFrameDetections *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  RootMessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RootMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RootMessage> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RootMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const FetchGame::Server *RootMessage::payload_as<FetchGame::Server>() const {
  return payload_as_FetchGame_Server();
}

template<> inline const Orange::VisionData::YoloFrameDetections *RootMessage::payload_as<Orange::VisionData::YoloFrameDetections>() const {
  return payload_as_Orange_VisionData_YoloFrameDetections();
}

struct RootMessageBuilder {
  typedef RootMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(Orange::Network::Payload payload_type) {
    fbb_.AddElement<uint8_t>(RootMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(RootMessage::VT_PAYLOAD, payload);
  }
  explicit RootMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RootMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RootMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RootMessage> CreateRootMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Orange::Network::Payload payload_type = Orange::Network::Payload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  RootMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<RootMessage> CreateRootMessage(::flatbuffers::FlatBufferBuilder &_fbb, const RootMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline RootMessageT *RootMessage::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RootMessageT>(new RootMessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RootMessage::UnPackTo(RootMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = Orange::Network::PayloadUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<RootMessage> RootMessage::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RootMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRootMessage(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RootMessage> CreateRootMessage(::flatbuffers::FlatBufferBuilder &_fbb, const RootMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RootMessageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return Orange::Network::CreateRootMessage(
      _fbb,
      _payload_type,
      _payload);
}

inline bool VerifyPayload(::flatbuffers::Verifier &verifier, const void *obj, Payload type) {
  switch (type) {
    case Payload_NONE: {
      return true;
    }
    case Payload_FetchGame_Server: {
      auto ptr = reinterpret_cast<const FetchGame::Server *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Orange_VisionData_YoloFrameDetections: {
      auto ptr = reinterpret_cast<const Orange::VisionData::YoloFrameDetections *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPayload(
        verifier,  values->Get(i), types->GetEnum<Payload>(i))) {
      return false;
    }
  }
  return true;
}

inline void *PayloadUnion::UnPack(const void *obj, Payload type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case Payload_FetchGame_Server: {
      auto ptr = reinterpret_cast<const FetchGame::Server *>(obj);
      return ptr->UnPack(resolver);
    }
    case Payload_Orange_VisionData_YoloFrameDetections: {
      auto ptr = reinterpret_cast<const Orange::VisionData::YoloFrameDetections *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> PayloadUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case Payload_FetchGame_Server: {
      auto ptr = reinterpret_cast<const FetchGame::ServerT *>(value);
      return CreateServer(_fbb, ptr, _rehasher).Union();
    }
    case Payload_Orange_VisionData_YoloFrameDetections: {
      auto ptr = reinterpret_cast<const Orange::VisionData::YoloFrameDetectionsT *>(value);
      return CreateYoloFrameDetections(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline PayloadUnion::PayloadUnion(const PayloadUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Payload_FetchGame_Server: {
      value = new FetchGame::ServerT(*reinterpret_cast<FetchGame::ServerT *>(u.value));
      break;
    }
    case Payload_Orange_VisionData_YoloFrameDetections: {
      value = new Orange::VisionData::YoloFrameDetectionsT(*reinterpret_cast<Orange::VisionData::YoloFrameDetectionsT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void PayloadUnion::Reset() {
  switch (type) {
    case Payload_FetchGame_Server: {
      auto ptr = reinterpret_cast<FetchGame::ServerT *>(value);
      delete ptr;
      break;
    }
    case Payload_Orange_VisionData_YoloFrameDetections: {
      auto ptr = reinterpret_cast<Orange::VisionData::YoloFrameDetectionsT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Payload_NONE;
}

inline const Orange::Network::RootMessage *GetRootMessage(const void *buf) {
  return ::flatbuffers::GetRoot<Orange::Network::RootMessage>(buf);
}

inline const Orange::Network::RootMessage *GetSizePrefixedRootMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Orange::Network::RootMessage>(buf);
}

inline const char *RootMessageIdentifier() {
  return "ORNG";
}

inline bool RootMessageBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, RootMessageIdentifier());
}

inline bool SizePrefixedRootMessageBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, RootMessageIdentifier(), true);
}

inline bool VerifyRootMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Orange::Network::RootMessage>(RootMessageIdentifier());
}

inline bool VerifySizePrefixedRootMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Orange::Network::RootMessage>(RootMessageIdentifier());
}

inline void FinishRootMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Orange::Network::RootMessage> root) {
  fbb.Finish(root, RootMessageIdentifier());
}

inline void FinishSizePrefixedRootMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Orange::Network::RootMessage> root) {
  fbb.FinishSizePrefixed(root, RootMessageIdentifier());
}

inline std::unique_ptr<Orange::Network::RootMessageT> UnPackRootMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<Orange::Network::RootMessageT>(GetRootMessage(buf)->UnPack(res));
}

inline std::unique_ptr<Orange::Network::RootMessageT> UnPackSizePrefixedRootMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<Orange::Network::RootMessageT>(GetSizePrefixedRootMessage(buf)->UnPack(res));
}

}  // namespace Network
}  // namespace Orange

#endif  // FLATBUFFERS_GENERATED_MESSAGEWRAPPER_ORANGE_NETWORK_H_
