// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OBJ_OBJ_H_
#define FLATBUFFERS_GENERATED_OBJ_OBJ_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace Obj {

struct obb;
struct obbBuilder;

struct obj_msg;
struct obj_msgBuilder;

struct obb FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef obbBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CX = 4,
    VT_CY = 6,
    VT_W = 8,
    VT_H = 10,
    VT_THETA = 12,
    VT_LABEL = 14
  };
  float cx() const {
    return GetField<float>(VT_CX, 0.0f);
  }
  bool mutate_cx(float _cx = 0.0f) {
    return SetField<float>(VT_CX, _cx, 0.0f);
  }
  float cy() const {
    return GetField<float>(VT_CY, 0.0f);
  }
  bool mutate_cy(float _cy = 0.0f) {
    return SetField<float>(VT_CY, _cy, 0.0f);
  }
  float w() const {
    return GetField<float>(VT_W, 0.0f);
  }
  bool mutate_w(float _w = 0.0f) {
    return SetField<float>(VT_W, _w, 0.0f);
  }
  float h() const {
    return GetField<float>(VT_H, 0.0f);
  }
  bool mutate_h(float _h = 0.0f) {
    return SetField<float>(VT_H, _h, 0.0f);
  }
  float theta() const {
    return GetField<float>(VT_THETA, 0.0f);
  }
  bool mutate_theta(float _theta = 0.0f) {
    return SetField<float>(VT_THETA, _theta, 0.0f);
  }
  float label() const {
    return GetField<float>(VT_LABEL, 0.0f);
  }
  bool mutate_label(float _label = 0.0f) {
    return SetField<float>(VT_LABEL, _label, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_CX, 4) &&
           VerifyField<float>(verifier, VT_CY, 4) &&
           VerifyField<float>(verifier, VT_W, 4) &&
           VerifyField<float>(verifier, VT_H, 4) &&
           VerifyField<float>(verifier, VT_THETA, 4) &&
           VerifyField<float>(verifier, VT_LABEL, 4) &&
           verifier.EndTable();
  }
};

struct obbBuilder {
  typedef obb Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cx(float cx) {
    fbb_.AddElement<float>(obb::VT_CX, cx, 0.0f);
  }
  void add_cy(float cy) {
    fbb_.AddElement<float>(obb::VT_CY, cy, 0.0f);
  }
  void add_w(float w) {
    fbb_.AddElement<float>(obb::VT_W, w, 0.0f);
  }
  void add_h(float h) {
    fbb_.AddElement<float>(obb::VT_H, h, 0.0f);
  }
  void add_theta(float theta) {
    fbb_.AddElement<float>(obb::VT_THETA, theta, 0.0f);
  }
  void add_label(float label) {
    fbb_.AddElement<float>(obb::VT_LABEL, label, 0.0f);
  }
  explicit obbBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<obb> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<obb>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<obb> Createobb(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float cx = 0.0f,
    float cy = 0.0f,
    float w = 0.0f,
    float h = 0.0f,
    float theta = 0.0f,
    float label = 0.0f) {
  obbBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_theta(theta);
  builder_.add_h(h);
  builder_.add_w(w);
  builder_.add_cy(cy);
  builder_.add_cx(cx);
  return builder_.Finish();
}

struct obj_msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef obj_msgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CYLINDER1 = 4,
    VT_CYLINDER2 = 6
  };
  const Obj::obb *cylinder1() const {
    return GetPointer<const Obj::obb *>(VT_CYLINDER1);
  }
  Obj::obb *mutable_cylinder1() {
    return GetPointer<Obj::obb *>(VT_CYLINDER1);
  }
  const Obj::obb *cylinder2() const {
    return GetPointer<const Obj::obb *>(VT_CYLINDER2);
  }
  Obj::obb *mutable_cylinder2() {
    return GetPointer<Obj::obb *>(VT_CYLINDER2);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CYLINDER1) &&
           verifier.VerifyTable(cylinder1()) &&
           VerifyOffset(verifier, VT_CYLINDER2) &&
           verifier.VerifyTable(cylinder2()) &&
           verifier.EndTable();
  }
};

struct obj_msgBuilder {
  typedef obj_msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cylinder1(::flatbuffers::Offset<Obj::obb> cylinder1) {
    fbb_.AddOffset(obj_msg::VT_CYLINDER1, cylinder1);
  }
  void add_cylinder2(::flatbuffers::Offset<Obj::obb> cylinder2) {
    fbb_.AddOffset(obj_msg::VT_CYLINDER2, cylinder2);
  }
  explicit obj_msgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<obj_msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<obj_msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<obj_msg> Createobj_msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Obj::obb> cylinder1 = 0,
    ::flatbuffers::Offset<Obj::obb> cylinder2 = 0) {
  obj_msgBuilder builder_(_fbb);
  builder_.add_cylinder2(cylinder2);
  builder_.add_cylinder1(cylinder1);
  return builder_.Finish();
}

inline const Obj::obj_msg *Getobj_msg(const void *buf) {
  return ::flatbuffers::GetRoot<Obj::obj_msg>(buf);
}

inline const Obj::obj_msg *GetSizePrefixedobj_msg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Obj::obj_msg>(buf);
}

inline obj_msg *GetMutableobj_msg(void *buf) {
  return ::flatbuffers::GetMutableRoot<obj_msg>(buf);
}

inline Obj::obj_msg *GetMutableSizePrefixedobj_msg(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<Obj::obj_msg>(buf);
}

inline bool Verifyobj_msgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Obj::obj_msg>(nullptr);
}

inline bool VerifySizePrefixedobj_msgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Obj::obj_msg>(nullptr);
}

inline const char *obj_msgExtension() {
  return "bfbs";
}

inline void Finishobj_msgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Obj::obj_msg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedobj_msgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Obj::obj_msg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Obj

#endif  // FLATBUFFERS_GENERATED_OBJ_OBJ_H_
