// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OBJPOSE_OBJPOSE_H_
#define FLATBUFFERS_GENERATED_OBJPOSE_OBJPOSE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace ObjPose {

struct pose2d;
struct pose2dBuilder;

struct obj_pose_msg;
struct obj_pose_msgBuilder;

struct pose2d FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef pose2dBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_THETA = 8,
    VT_PROB = 10,
    VT_LABEL = 12
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  bool mutate_x(float _x = 0.0f) {
    return SetField<float>(VT_X, _x, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  bool mutate_y(float _y = 0.0f) {
    return SetField<float>(VT_Y, _y, 0.0f);
  }
  float theta() const {
    return GetField<float>(VT_THETA, 0.0f);
  }
  bool mutate_theta(float _theta = 0.0f) {
    return SetField<float>(VT_THETA, _theta, 0.0f);
  }
  float prob() const {
    return GetField<float>(VT_PROB, 0.0f);
  }
  bool mutate_prob(float _prob = 0.0f) {
    return SetField<float>(VT_PROB, _prob, 0.0f);
  }
  float label() const {
    return GetField<float>(VT_LABEL, 0.0f);
  }
  bool mutate_label(float _label = 0.0f) {
    return SetField<float>(VT_LABEL, _label, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_THETA, 4) &&
           VerifyField<float>(verifier, VT_PROB, 4) &&
           VerifyField<float>(verifier, VT_LABEL, 4) &&
           verifier.EndTable();
  }
};

struct pose2dBuilder {
  typedef pose2d Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(pose2d::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(pose2d::VT_Y, y, 0.0f);
  }
  void add_theta(float theta) {
    fbb_.AddElement<float>(pose2d::VT_THETA, theta, 0.0f);
  }
  void add_prob(float prob) {
    fbb_.AddElement<float>(pose2d::VT_PROB, prob, 0.0f);
  }
  void add_label(float label) {
    fbb_.AddElement<float>(pose2d::VT_LABEL, label, 0.0f);
  }
  explicit pose2dBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<pose2d> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<pose2d>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<pose2d> Createpose2d(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float theta = 0.0f,
    float prob = 0.0f,
    float label = 0.0f) {
  pose2dBuilder builder_(_fbb);
  builder_.add_label(label);
  builder_.add_prob(prob);
  builder_.add_theta(theta);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct obj_pose_msg FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef obj_pose_msgBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MOUSE = 4,
    VT_BALL = 6
  };
  const ObjPose::pose2d *mouse() const {
    return GetPointer<const ObjPose::pose2d *>(VT_MOUSE);
  }
  ObjPose::pose2d *mutable_mouse() {
    return GetPointer<ObjPose::pose2d *>(VT_MOUSE);
  }
  const ObjPose::pose2d *ball() const {
    return GetPointer<const ObjPose::pose2d *>(VT_BALL);
  }
  ObjPose::pose2d *mutable_ball() {
    return GetPointer<ObjPose::pose2d *>(VT_BALL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MOUSE) &&
           verifier.VerifyTable(mouse()) &&
           VerifyOffset(verifier, VT_BALL) &&
           verifier.VerifyTable(ball()) &&
           verifier.EndTable();
  }
};

struct obj_pose_msgBuilder {
  typedef obj_pose_msg Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mouse(::flatbuffers::Offset<ObjPose::pose2d> mouse) {
    fbb_.AddOffset(obj_pose_msg::VT_MOUSE, mouse);
  }
  void add_ball(::flatbuffers::Offset<ObjPose::pose2d> ball) {
    fbb_.AddOffset(obj_pose_msg::VT_BALL, ball);
  }
  explicit obj_pose_msgBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<obj_pose_msg> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<obj_pose_msg>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<obj_pose_msg> Createobj_pose_msg(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ObjPose::pose2d> mouse = 0,
    ::flatbuffers::Offset<ObjPose::pose2d> ball = 0) {
  obj_pose_msgBuilder builder_(_fbb);
  builder_.add_ball(ball);
  builder_.add_mouse(mouse);
  return builder_.Finish();
}

inline const ObjPose::obj_pose_msg *Getobj_pose_msg(const void *buf) {
  return ::flatbuffers::GetRoot<ObjPose::obj_pose_msg>(buf);
}

inline const ObjPose::obj_pose_msg *GetSizePrefixedobj_pose_msg(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ObjPose::obj_pose_msg>(buf);
}

inline obj_pose_msg *GetMutableobj_pose_msg(void *buf) {
  return ::flatbuffers::GetMutableRoot<obj_pose_msg>(buf);
}

inline ObjPose::obj_pose_msg *GetMutableSizePrefixedobj_pose_msg(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<ObjPose::obj_pose_msg>(buf);
}

inline bool Verifyobj_pose_msgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ObjPose::obj_pose_msg>(nullptr);
}

inline bool VerifySizePrefixedobj_pose_msgBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ObjPose::obj_pose_msg>(nullptr);
}

inline const char *obj_pose_msgExtension() {
  return "bfbs";
}

inline void Finishobj_pose_msgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ObjPose::obj_pose_msg> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedobj_pose_msgBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ObjPose::obj_pose_msg> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace ObjPose

#endif  // FLATBUFFERS_GENERATED_OBJPOSE_OBJPOSE_H_
