// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_YOLOPAYLOAD_ORANGE_VISIONDATA_H_
#define FLATBUFFERS_GENERATED_YOLOPAYLOAD_ORANGE_VISIONDATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace Orange {
namespace VisionData {

struct BoundingBox;

struct Detection;
struct DetectionBuilder;

struct YoloFrameDetections;
struct YoloFrameDetectionsBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BoundingBox FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float width_;
  float height_;
  int32_t label_;
  float probability_;

 public:
  BoundingBox()
      : x_(0),
        y_(0),
        width_(0),
        height_(0),
        label_(0),
        probability_(0) {
  }
  BoundingBox(float _x, float _y, float _width, float _height, int32_t _label, float _probability)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        width_(::flatbuffers::EndianScalar(_width)),
        height_(::flatbuffers::EndianScalar(_height)),
        label_(::flatbuffers::EndianScalar(_label)),
        probability_(::flatbuffers::EndianScalar(_probability)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float width() const {
    return ::flatbuffers::EndianScalar(width_);
  }
  float height() const {
    return ::flatbuffers::EndianScalar(height_);
  }
  int32_t label() const {
    return ::flatbuffers::EndianScalar(label_);
  }
  float probability() const {
    return ::flatbuffers::EndianScalar(probability_);
  }
};
FLATBUFFERS_STRUCT_END(BoundingBox, 24);

struct Detection FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DetectionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BOX = 4
  };
  const Orange::VisionData::BoundingBox *box() const {
    return GetStruct<const Orange::VisionData::BoundingBox *>(VT_BOX);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Orange::VisionData::BoundingBox>(verifier, VT_BOX, 4) &&
           verifier.EndTable();
  }
};

struct DetectionBuilder {
  typedef Detection Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_box(const Orange::VisionData::BoundingBox *box) {
    fbb_.AddStruct(Detection::VT_BOX, box);
  }
  explicit DetectionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Detection> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Detection>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Detection> CreateDetection(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Orange::VisionData::BoundingBox *box = nullptr) {
  DetectionBuilder builder_(_fbb);
  builder_.add_box(box);
  return builder_.Finish();
}

struct YoloFrameDetections FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef YoloFrameDetectionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAMERA_SERIAL = 4,
    VT_TIMESTAMP = 6,
    VT_FRAME_ID = 8,
    VT_DETECTIONS = 10
  };
  const ::flatbuffers::String *camera_serial() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CAMERA_SERIAL);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t frame_id() const {
    return GetField<uint64_t>(VT_FRAME_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>> *detections() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>> *>(VT_DETECTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CAMERA_SERIAL) &&
           verifier.VerifyString(camera_serial()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_FRAME_ID, 8) &&
           VerifyOffset(verifier, VT_DETECTIONS) &&
           verifier.VerifyVector(detections()) &&
           verifier.VerifyVectorOfTables(detections()) &&
           verifier.EndTable();
  }
};

struct YoloFrameDetectionsBuilder {
  typedef YoloFrameDetections Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_camera_serial(::flatbuffers::Offset<::flatbuffers::String> camera_serial) {
    fbb_.AddOffset(YoloFrameDetections::VT_CAMERA_SERIAL, camera_serial);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(YoloFrameDetections::VT_TIMESTAMP, timestamp, 0);
  }
  void add_frame_id(uint64_t frame_id) {
    fbb_.AddElement<uint64_t>(YoloFrameDetections::VT_FRAME_ID, frame_id, 0);
  }
  void add_detections(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>>> detections) {
    fbb_.AddOffset(YoloFrameDetections::VT_DETECTIONS, detections);
  }
  explicit YoloFrameDetectionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<YoloFrameDetections> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<YoloFrameDetections>(end);
    fbb_.Required(o, YoloFrameDetections::VT_CAMERA_SERIAL);
    return o;
  }
};

inline ::flatbuffers::Offset<YoloFrameDetections> CreateYoloFrameDetections(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> camera_serial = 0,
    uint64_t timestamp = 0,
    uint64_t frame_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>>> detections = 0) {
  YoloFrameDetectionsBuilder builder_(_fbb);
  builder_.add_frame_id(frame_id);
  builder_.add_timestamp(timestamp);
  builder_.add_detections(detections);
  builder_.add_camera_serial(camera_serial);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<YoloFrameDetections> CreateYoloFrameDetectionsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *camera_serial = nullptr,
    uint64_t timestamp = 0,
    uint64_t frame_id = 0,
    const std::vector<::flatbuffers::Offset<Orange::VisionData::Detection>> *detections = nullptr) {
  auto camera_serial__ = camera_serial ? _fbb.CreateString(camera_serial) : 0;
  auto detections__ = detections ? _fbb.CreateVector<::flatbuffers::Offset<Orange::VisionData::Detection>>(*detections) : 0;
  return Orange::VisionData::CreateYoloFrameDetections(
      _fbb,
      camera_serial__,
      timestamp,
      frame_id,
      detections__);
}

inline const Orange::VisionData::YoloFrameDetections *GetYoloFrameDetections(const void *buf) {
  return ::flatbuffers::GetRoot<Orange::VisionData::YoloFrameDetections>(buf);
}

inline const Orange::VisionData::YoloFrameDetections *GetSizePrefixedYoloFrameDetections(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Orange::VisionData::YoloFrameDetections>(buf);
}

inline bool VerifyYoloFrameDetectionsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Orange::VisionData::YoloFrameDetections>(nullptr);
}

inline bool VerifySizePrefixedYoloFrameDetectionsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Orange::VisionData::YoloFrameDetections>(nullptr);
}

inline void FinishYoloFrameDetectionsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Orange::VisionData::YoloFrameDetections> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedYoloFrameDetectionsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Orange::VisionData::YoloFrameDetections> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace VisionData
}  // namespace Orange

#endif  // FLATBUFFERS_GENERATED_YOLOPAYLOAD_ORANGE_VISIONDATA_H_
