// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_YOLOPAYLOAD_ORANGE_VISIONDATA_H_
#define FLATBUFFERS_GENERATED_YOLOPAYLOAD_ORANGE_VISIONDATA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace Orange {
namespace VisionData {

struct BoundingBox;

struct Detection;
struct DetectionBuilder;
struct DetectionT;

struct YoloFrameDetections;
struct YoloFrameDetectionsBuilder;
struct YoloFrameDetectionsT;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) BoundingBox FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float width_;
  float height_;
  int32_t label_;
  float probability_;

 public:
  BoundingBox()
      : x_(0),
        y_(0),
        width_(0),
        height_(0),
        label_(0),
        probability_(0) {
  }
  BoundingBox(float _x, float _y, float _width, float _height, int32_t _label, float _probability)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        width_(::flatbuffers::EndianScalar(_width)),
        height_(::flatbuffers::EndianScalar(_height)),
        label_(::flatbuffers::EndianScalar(_label)),
        probability_(::flatbuffers::EndianScalar(_probability)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float width() const {
    return ::flatbuffers::EndianScalar(width_);
  }
  float height() const {
    return ::flatbuffers::EndianScalar(height_);
  }
  int32_t label() const {
    return ::flatbuffers::EndianScalar(label_);
  }
  float probability() const {
    return ::flatbuffers::EndianScalar(probability_);
  }
};
FLATBUFFERS_STRUCT_END(BoundingBox, 24);

struct DetectionT : public ::flatbuffers::NativeTable {
  typedef Detection TableType;
  std::unique_ptr<Orange::VisionData::BoundingBox> box{};
  DetectionT() = default;
  DetectionT(const DetectionT &o);
  DetectionT(DetectionT&&) FLATBUFFERS_NOEXCEPT = default;
  DetectionT &operator=(DetectionT o) FLATBUFFERS_NOEXCEPT;
};

struct Detection FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DetectionT NativeTableType;
  typedef DetectionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BOX = 4
  };
  const Orange::VisionData::BoundingBox *box() const {
    return GetStruct<const Orange::VisionData::BoundingBox *>(VT_BOX);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Orange::VisionData::BoundingBox>(verifier, VT_BOX, 4) &&
           verifier.EndTable();
  }
  DetectionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DetectionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Detection> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DetectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DetectionBuilder {
  typedef Detection Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_box(const Orange::VisionData::BoundingBox *box) {
    fbb_.AddStruct(Detection::VT_BOX, box);
  }
  explicit DetectionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Detection> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Detection>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Detection> CreateDetection(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const Orange::VisionData::BoundingBox *box = nullptr) {
  DetectionBuilder builder_(_fbb);
  builder_.add_box(box);
  return builder_.Finish();
}

::flatbuffers::Offset<Detection> CreateDetection(::flatbuffers::FlatBufferBuilder &_fbb, const DetectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct YoloFrameDetectionsT : public ::flatbuffers::NativeTable {
  typedef YoloFrameDetections TableType;
  std::string camera_serial{};
  uint64_t timestamp = 0;
  uint64_t frame_id = 0;
  std::vector<std::unique_ptr<Orange::VisionData::DetectionT>> detections{};
  YoloFrameDetectionsT() = default;
  YoloFrameDetectionsT(const YoloFrameDetectionsT &o);
  YoloFrameDetectionsT(YoloFrameDetectionsT&&) FLATBUFFERS_NOEXCEPT = default;
  YoloFrameDetectionsT &operator=(YoloFrameDetectionsT o) FLATBUFFERS_NOEXCEPT;
};

struct YoloFrameDetections FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef YoloFrameDetectionsT NativeTableType;
  typedef YoloFrameDetectionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAMERA_SERIAL = 4,
    VT_TIMESTAMP = 6,
    VT_FRAME_ID = 8,
    VT_DETECTIONS = 10
  };
  const ::flatbuffers::String *camera_serial() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CAMERA_SERIAL);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint64_t frame_id() const {
    return GetField<uint64_t>(VT_FRAME_ID, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>> *detections() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>> *>(VT_DETECTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CAMERA_SERIAL) &&
           verifier.VerifyString(camera_serial()) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyField<uint64_t>(verifier, VT_FRAME_ID, 8) &&
           VerifyOffset(verifier, VT_DETECTIONS) &&
           verifier.VerifyVector(detections()) &&
           verifier.VerifyVectorOfTables(detections()) &&
           verifier.EndTable();
  }
  YoloFrameDetectionsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(YoloFrameDetectionsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<YoloFrameDetections> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const YoloFrameDetectionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct YoloFrameDetectionsBuilder {
  typedef YoloFrameDetections Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_camera_serial(::flatbuffers::Offset<::flatbuffers::String> camera_serial) {
    fbb_.AddOffset(YoloFrameDetections::VT_CAMERA_SERIAL, camera_serial);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(YoloFrameDetections::VT_TIMESTAMP, timestamp, 0);
  }
  void add_frame_id(uint64_t frame_id) {
    fbb_.AddElement<uint64_t>(YoloFrameDetections::VT_FRAME_ID, frame_id, 0);
  }
  void add_detections(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>>> detections) {
    fbb_.AddOffset(YoloFrameDetections::VT_DETECTIONS, detections);
  }
  explicit YoloFrameDetectionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<YoloFrameDetections> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<YoloFrameDetections>(end);
    fbb_.Required(o, YoloFrameDetections::VT_CAMERA_SERIAL);
    return o;
  }
};

inline ::flatbuffers::Offset<YoloFrameDetections> CreateYoloFrameDetections(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> camera_serial = 0,
    uint64_t timestamp = 0,
    uint64_t frame_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Orange::VisionData::Detection>>> detections = 0) {
  YoloFrameDetectionsBuilder builder_(_fbb);
  builder_.add_frame_id(frame_id);
  builder_.add_timestamp(timestamp);
  builder_.add_detections(detections);
  builder_.add_camera_serial(camera_serial);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<YoloFrameDetections> CreateYoloFrameDetectionsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *camera_serial = nullptr,
    uint64_t timestamp = 0,
    uint64_t frame_id = 0,
    const std::vector<::flatbuffers::Offset<Orange::VisionData::Detection>> *detections = nullptr) {
  auto camera_serial__ = camera_serial ? _fbb.CreateString(camera_serial) : 0;
  auto detections__ = detections ? _fbb.CreateVector<::flatbuffers::Offset<Orange::VisionData::Detection>>(*detections) : 0;
  return Orange::VisionData::CreateYoloFrameDetections(
      _fbb,
      camera_serial__,
      timestamp,
      frame_id,
      detections__);
}

::flatbuffers::Offset<YoloFrameDetections> CreateYoloFrameDetections(::flatbuffers::FlatBufferBuilder &_fbb, const YoloFrameDetectionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline DetectionT::DetectionT(const DetectionT &o)
      : box((o.box) ? new Orange::VisionData::BoundingBox(*o.box) : nullptr) {
}

inline DetectionT &DetectionT::operator=(DetectionT o) FLATBUFFERS_NOEXCEPT {
  std::swap(box, o.box);
  return *this;
}

inline DetectionT *Detection::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DetectionT>(new DetectionT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Detection::UnPackTo(DetectionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = box(); if (_e) _o->box = std::unique_ptr<Orange::VisionData::BoundingBox>(new Orange::VisionData::BoundingBox(*_e)); }
}

inline ::flatbuffers::Offset<Detection> Detection::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DetectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDetection(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Detection> CreateDetection(::flatbuffers::FlatBufferBuilder &_fbb, const DetectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DetectionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _box = _o->box ? _o->box.get() : nullptr;
  return Orange::VisionData::CreateDetection(
      _fbb,
      _box);
}

inline YoloFrameDetectionsT::YoloFrameDetectionsT(const YoloFrameDetectionsT &o)
      : camera_serial(o.camera_serial),
        timestamp(o.timestamp),
        frame_id(o.frame_id) {
  detections.reserve(o.detections.size());
  for (const auto &detections_ : o.detections) { detections.emplace_back((detections_) ? new Orange::VisionData::DetectionT(*detections_) : nullptr); }
}

inline YoloFrameDetectionsT &YoloFrameDetectionsT::operator=(YoloFrameDetectionsT o) FLATBUFFERS_NOEXCEPT {
  std::swap(camera_serial, o.camera_serial);
  std::swap(timestamp, o.timestamp);
  std::swap(frame_id, o.frame_id);
  std::swap(detections, o.detections);
  return *this;
}

inline YoloFrameDetectionsT *YoloFrameDetections::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<YoloFrameDetectionsT>(new YoloFrameDetectionsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void YoloFrameDetections::UnPackTo(YoloFrameDetectionsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = camera_serial(); if (_e) _o->camera_serial = _e->str(); }
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = frame_id(); _o->frame_id = _e; }
  { auto _e = detections(); if (_e) { _o->detections.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->detections[_i]) { _e->Get(_i)->UnPackTo(_o->detections[_i].get(), _resolver); } else { _o->detections[_i] = std::unique_ptr<Orange::VisionData::DetectionT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->detections.resize(0); } }
}

inline ::flatbuffers::Offset<YoloFrameDetections> YoloFrameDetections::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const YoloFrameDetectionsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateYoloFrameDetections(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<YoloFrameDetections> CreateYoloFrameDetections(::flatbuffers::FlatBufferBuilder &_fbb, const YoloFrameDetectionsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const YoloFrameDetectionsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _camera_serial = _fbb.CreateString(_o->camera_serial);
  auto _timestamp = _o->timestamp;
  auto _frame_id = _o->frame_id;
  auto _detections = _o->detections.size() ? _fbb.CreateVector<::flatbuffers::Offset<Orange::VisionData::Detection>> (_o->detections.size(), [](size_t i, _VectorArgs *__va) { return CreateDetection(*__va->__fbb, __va->__o->detections[i].get(), __va->__rehasher); }, &_va ) : 0;
  return Orange::VisionData::CreateYoloFrameDetections(
      _fbb,
      _camera_serial,
      _timestamp,
      _frame_id,
      _detections);
}

inline const Orange::VisionData::YoloFrameDetections *GetYoloFrameDetections(const void *buf) {
  return ::flatbuffers::GetRoot<Orange::VisionData::YoloFrameDetections>(buf);
}

inline const Orange::VisionData::YoloFrameDetections *GetSizePrefixedYoloFrameDetections(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Orange::VisionData::YoloFrameDetections>(buf);
}

inline bool VerifyYoloFrameDetectionsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Orange::VisionData::YoloFrameDetections>(nullptr);
}

inline bool VerifySizePrefixedYoloFrameDetectionsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Orange::VisionData::YoloFrameDetections>(nullptr);
}

inline void FinishYoloFrameDetectionsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Orange::VisionData::YoloFrameDetections> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedYoloFrameDetectionsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Orange::VisionData::YoloFrameDetections> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<Orange::VisionData::YoloFrameDetectionsT> UnPackYoloFrameDetections(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<Orange::VisionData::YoloFrameDetectionsT>(GetYoloFrameDetections(buf)->UnPack(res));
}

inline std::unique_ptr<Orange::VisionData::YoloFrameDetectionsT> UnPackSizePrefixedYoloFrameDetections(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<Orange::VisionData::YoloFrameDetectionsT>(GetSizePrefixedYoloFrameDetections(buf)->UnPack(res));
}

}  // namespace VisionData
}  // namespace Orange

#endif  // FLATBUFFERS_GENERATED_YOLOPAYLOAD_ORANGE_VISIONDATA_H_
